package dev.aivillages.providers;

import dev.aivillages.core.kernel.*;
import org.junit.jupiter.api.Test;
import java.util.ArrayDeque;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import static dev.aivillages.core.kernel.Budgets.Kind;
import static org.junit.jupiter.api.Assertions.*;

/** Controlled backend, actual IMP-005 transport and IMP-014 accounting. No live inference claim. */
class BrokerAdapterIntegrationTest {
    static final String CANDIDATE="{\"schema\":1,\"capability\":\"cognitivecraft:deliver_wheat\",\"capabilityVersion\":1,\"dependencies\":[],\"body\":{\"loop\":{\"count\":{\"param\":\"amount\"},\"body\":{\"prepare\":\"cognitivecraft:harvest_next_wheat\",\"wait\":{\"primitive\":\"cognitivecraft:observe_inventory\",\"count\":30},\"finish\":[\"cognitivecraft:pickup_tracked_wheat\",\"cognitivecraft:transfer_wheat\"]}},\"result\":{\"param\":\"amount\"}}}";
    static Generation.Request peer(Generation.Request r){return new Generation.Request(UUID.randomUUID(),r.bound(),r.capability(),r.primitives(),r.dependencies(),r.role(),r.context());}
    static Budgets.InferenceLimits limits(GenerationChecks.Fixture f,long deadline,long output){return new Budgets.InferenceLimits(new Budgets.Limits(Map.of(Kind.CALLS,2L,Kind.REPAIRS,1L,Kind.INPUT_BYTES,32768L,Kind.OUTPUT_BYTES,output),deadline),16384,output);}
    static AIWorkBroker broker(GenerationChecks.Fixture f){return new AIWorkBroker(f.adapter,f.clock,AIWorkBroker.Settings.defaults(),AIWorkBroker.sessionLimits(f.clock.millis()),r->true,AIWorkBroker.Sharing.privateScopes());}
    @Test void actualAdapterCoalescesAndMetersOnePhysicalCallAndTwoBeneficiaries(){
        try(var f=new GenerationChecks.Fixture()){
            var broker=broker(f);var request=GenerationChecks.request(Generation.Role.INITIAL,"shared exact snapshot");var l=limits(f,f.clock.millis()+10000,8192);
            var left=new Budgets.Ledger(l.total(),f.clock);var right=new Budgets.Ledger(l.total(),f.clock);
            var a=broker.generate(request,l,left);var b=broker.generate(peer(request),l,right);broker.step();assertEquals(1,f.backend.sinks.size());
            f.backend.respond(0,CANDIDATE,100L,30L);broker.step();assertEquals(Generation.Outcome.CANDIDATE,a.result().toCompletableFuture().join().outcome());assertEquals(Generation.Outcome.CANDIDATE,b.result().toCompletableFuture().join().outcome());
            assertEquals(left.snapshot(),right.snapshot());assertEquals(1,left.snapshot().get(Kind.CALLS));assertEquals(f.backend.bodies.getFirst().getBytes(java.nio.charset.StandardCharsets.UTF_8).length,broker.stats().inputBytes());assertEquals(CANDIDATE.getBytes(java.nio.charset.StandardCharsets.UTF_8).length,broker.stats().outputBytes());
        }
    }
    @Test void actualAdapterOneSubscriberCancellationKeepsRemainingResult(){try(var f=new GenerationChecks.Fixture()){var broker=broker(f);var request=GenerationChecks.request(Generation.Role.INITIAL,"same");var l=limits(f,f.clock.millis()+10000,8192);var a=broker.generate(request,l,new Budgets.Ledger(l.total(),f.clock));var b=broker.generate(peer(request),l,new Budgets.Ledger(l.total(),f.clock));broker.step();a.cancel();assertEquals(0,f.backend.cancels);f.backend.respond(0,CANDIDATE,null,null);broker.step();assertNull(a.result().toCompletableFuture().join().candidateIr());assertEquals(Generation.Outcome.CANDIDATE,b.result().toCompletableFuture().join().outcome());}}
    @Test void actualAdapterUnconfirmedStopCannotStartReplacement(){try(var f=new GenerationChecks.Fixture()){var broker=broker(f);var request=GenerationChecks.request(Generation.Role.INITIAL,"first");var l=limits(f,f.clock.millis()+10000,8192);var a=broker.generate(request,l,new Budgets.Ledger(l.total(),f.clock));broker.step();a.cancel();broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"incompatible replacement"),l,new Budgets.Ledger(l.total(),f.clock));for(int i=0;i<20;i++)broker.step();assertEquals(1,f.backend.sinks.size());assertEquals(1,broker.stats().unconfirmed());f.backend.respond(0,CANDIDATE,null,null);broker.step();assertEquals(2,f.backend.sinks.size());assertEquals(Generation.Outcome.ABANDONED,a.result().toCompletableFuture().join().outcome());}}
    @Test void actualAdapterConfirmedStopReleasesHardwareSlot(){try(var f=new GenerationChecks.Fixture()){f.backend.confirmed=true;var broker=broker(f);var l=limits(f,f.clock.millis()+10000,8192);var a=broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"first"),l,new Budgets.Ledger(l.total(),f.clock));broker.step();a.cancel();broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"second"),l,new Budgets.Ledger(l.total(),f.clock));broker.step();assertEquals(2,f.backend.sinks.size());assertEquals(Generation.Compute.STOP_CONFIRMED,a.compute());}}
    @Test void actualAdapterEnforcesLowerSubscriberByteLimit(){try(var f=new GenerationChecks.Fixture()){var broker=broker(f);var request=GenerationChecks.request(Generation.Role.INITIAL,"same");var l=limits(f,f.clock.millis()+10000,8192);var a=broker.generate(request,l,new Budgets.Ledger(l.total(),f.clock));var lower=limits(f,f.clock.millis()+10000,100);var root=new Budgets.Ledger(lower.total(),f.clock);var b=broker.generate(peer(request),lower,root);broker.step();f.backend.respond(0,CANDIDATE,null,null);broker.step();assertEquals(Generation.Outcome.LIMIT,a.result().toCompletableFuture().join().outcome());assertEquals(Generation.Outcome.LIMIT,b.result().toCompletableFuture().join().outcome());assertEquals(100,root.snapshot().get(Kind.OUTPUT_BYTES));}}
    @Test void actualAdapterColdPreparationUsesOriginalDeadline(){var preparation=new ArrayDeque<Runnable>();try(var f=new GenerationChecks.Fixture(preparation::add)){var broker=broker(f);var l=limits(f,f.clock.millis()+10,8192);var root=new Budgets.Ledger(l.total(),f.clock);var a=broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"cold"),l,root);broker.step();f.clock.now+=11;preparation.remove().run();broker.step();assertEquals(Generation.Outcome.LIMIT,a.result().toCompletableFuture().join().outcome());assertEquals(0,f.backend.sinks.size());assertFalse(root.snapshot().containsKey(Kind.CALLS));}}
    @Test void cancelledPreparationCannotHoldSlotOrStartLateTransport(){var preparation=new ArrayDeque<Runnable>();try(var f=new GenerationChecks.Fixture(preparation::add)){var broker=broker(f);var l=limits(f,f.clock.millis()+10000,8192);var a=broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"cold"),l,new Budgets.Ledger(l.total(),f.clock));broker.step();a.cancel();broker.step();assertEquals(0,broker.stats().occupied());assertEquals(Generation.State.READY,f.adapter.status().state());while(!preparation.isEmpty())preparation.remove().run();assertTrue(f.backend.sinks.isEmpty());}}
    @Test void shutdownAndFreshBrokerDoNotReplayTransportOrMutateArtifacts(){try(var f=new GenerationChecks.Fixture()){var broker=broker(f);var l=limits(f,f.clock.millis()+10000,8192);broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"a"),l,new Budgets.Ledger(l.total(),f.clock));broker.step();broker.generate(GenerationChecks.request(Generation.Role.INITIAL,"b"),l,new Budgets.Ledger(l.total(),f.clock));broker.close();var fresh=broker(f);fresh.step();assertEquals(1,f.backend.sinks.size());assertEquals(0,fresh.stats().queuedWork());assertEquals(Generation.State.CANCELLING,fresh.status().state());}}
}
